version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: deloy-to-helm-repo
          environment:
            - GITHUB_PAGES_REPO: funkypenguin/helm-charts
          command: wget -O - https://raw.githubusercontent.com/funkypenguin/helm-github-pages/master/publish.sh | sh
