name: Testing

on: 
  push:
    paths:
      - 'charts/**'   
      - '.github/**'            
    ignore_branches:
      - 'master'

jobs:
  ct-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
          
      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.0.0-rc.2
        with:
          config: .ci/ct-config.yaml
          command: lint
        env:
          CT_CHECK_VERSION_INCREMENT: false

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0-rc.1
        with:
          install_local_path_provisioner: true
        # Only build a kind cluster if there are chart changes to test.
        if: steps.lint.outputs.changed == 'true'

      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v1.0.0-rc.2
        with:
          command: install
          config: .ci/ct-config.yaml
